const express=require('express');
const path=require('path');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'CAMBIA-ESTA-CLAVE-EMPODERARTE';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});

const today=()=>new Date().toISOString().slice(0,10);
const nextMonth=d=>{const x=new Date((d&&d>=today()?d:today())+'T12:00:00');x.setMonth(x.getMonth()+1);return x.toISOString().slice(0,10)};
const addMonths=(d,n)=>{const x=new Date((d&&d>=today()?d:today())+'T12:00:00');x.setMonth(x.getMonth()+Number(n||0));return x.toISOString().slice(0,10)};

async function init(){
  if(!process.env.DATABASE_URL) console.warn('DATABASE_URL no configurada: se requiere PostgreSQL para producción.');
  await pool.query(`
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'recepcion',active INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,last_login TIMESTAMP);
CREATE TABLE IF NOT EXISTS students(id SERIAL PRIMARY KEY,matricula TEXT UNIQUE,name TEXT NOT NULL,last_name TEXT NOT NULL,birth_date TEXT,phone TEXT,email TEXT,tutor TEXT,tutor_phone TEXT,plan TEXT DEFAULT 'Inicial',status TEXT DEFAULT 'Activo',enrollment_date TEXT NOT NULL,monthly_fee NUMERIC DEFAULT 0,due_date TEXT,benefit_level TEXT DEFAULT 'Base',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments(id SERIAL PRIMARY KEY,receipt_no TEXT UNIQUE NOT NULL,student_id INTEGER NOT NULL REFERENCES students(id),amount NUMERIC NOT NULL,method TEXT NOT NULL,concept TEXT DEFAULT 'Mensualidad',paid_at TEXT NOT NULL,period TEXT,notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS attendance(id SERIAL PRIMARY KEY,student_id INTEGER NOT NULL REFERENCES students(id),attended_at TEXT NOT NULL,discipline TEXT,group_name TEXT,status TEXT DEFAULT 'Presente',notes TEXT);
CREATE TABLE IF NOT EXISTS promotions(id SERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT,discount NUMERIC DEFAULT 0,kind TEXT DEFAULT 'Porcentaje',active INTEGER DEFAULT 1,expires_at TEXT);
CREATE TABLE IF NOT EXISTS benefits(id SERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT,level TEXT DEFAULT 'Base',active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS audit(id SERIAL PRIMARY KEY,user_id INTEGER,module TEXT,record_id INTEGER,action TEXT NOT NULL,detail TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS teachers(id SERIAL PRIMARY KEY,matricula TEXT UNIQUE,name TEXT NOT NULL,last_name TEXT NOT NULL,phone TEXT,email TEXT,discipline TEXT,rate_hour NUMERIC DEFAULT 0,status TEXT DEFAULT 'Activo',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS teacher_attendance(id SERIAL PRIMARY KEY,teacher_id INTEGER NOT NULL REFERENCES teachers(id),attended_at TEXT NOT NULL,entry_time TEXT,exit_time TEXT,discipline TEXT,notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS locker_plans(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,price NUMERIC NOT NULL DEFAULT 0,months INTEGER NOT NULL DEFAULT 1,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS lockers(id SERIAL PRIMARY KEY,number TEXT UNIQUE NOT NULL,student_id INTEGER REFERENCES students(id),plan_id INTEGER REFERENCES locker_plans(id),plan_name TEXT,price NUMERIC DEFAULT 0,months INTEGER DEFAULT 1,paid_at TEXT,due_date TEXT,status TEXT DEFAULT 'Activo',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS locker_payments(id SERIAL PRIMARY KEY,locker_id INTEGER NOT NULL REFERENCES lockers(id),amount NUMERIC NOT NULL,paid_at TEXT NOT NULL,method TEXT DEFAULT 'Efectivo',concept TEXT DEFAULT 'Renta de locker',period TEXT,notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS locker_penalties(id SERIAL PRIMARY KEY,locker_id INTEGER NOT NULL REFERENCES lockers(id),amount NUMERIC NOT NULL,reason TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS personal(id SERIAL PRIMARY KEY,matricula TEXT UNIQUE,name TEXT NOT NULL,last_name TEXT NOT NULL,position TEXT DEFAULT 'Recepción',area TEXT,phone TEXT,email TEXT,rate_hour NUMERIC DEFAULT 0,status TEXT DEFAULT 'Activo',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS personal_attendance(id SERIAL PRIMARY KEY,personal_id INTEGER NOT NULL REFERENCES personal(id),attended_at TEXT NOT NULL,entry_time TEXT,exit_time TEXT,activity TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY DEFAULT 1,config JSONB NOT NULL DEFAULT '{}'::jsonb,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS trash(id SERIAL PRIMARY KEY,entity_type TEXT NOT NULL,entity_id INTEGER,matricula TEXT,name TEXT,last_name TEXT,data JSONB,deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_by INTEGER REFERENCES users(id));
  `);
  const u=await pool.query('SELECT id FROM users WHERE email=$1',['director@empoderarte.local']);
  if(!u.rowCount) await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4)',['Director EmpoderArte','director@empoderarte.local',bcrypt.hashSync('empoderarte',10),'director']);
  const p=await pool.query('SELECT id FROM promotions LIMIT 1');
  if(!p.rowCount) await pool.query('INSERT INTO promotions(name,description,discount,kind) VALUES($1,$2,$3,$4)',['Bienvenida EmpoderArte','Promoción inicial para nuevos alumnos',10,'Porcentaje']);
  const b=await pool.query('SELECT id FROM benefits LIMIT 1');
  if(!b.rowCount){for(const x of ['Base','Plus','Premium','Elite']) await pool.query('INSERT INTO benefits(name,description,level) VALUES($1,$2,$3)',[x,'Beneficios del nivel '+x,x]);}
  const lp=await pool.query('SELECT id FROM locker_plans LIMIT 1');
  if(!lp.rowCount) for(const x of [['Mensual',100,1],['Semestral',550,6],['Anual',900,12]]) await pool.query('INSERT INTO locker_plans(name,price,months) VALUES($1,$2,$3)',x);
}

async function matricula(){const y=new Date().getFullYear();const r=await pool.query("SELECT COALESCE(MAX(CAST(SUBSTRING(matricula FROM 10) AS INTEGER)),0) n FROM students WHERE matricula LIKE $1",[`EMP-${y}-%`]);return `EMP-${y}-${String(Number(r.rows[0].n)+1).padStart(5,'0')}`}
async function receipt(){const y=new Date().getFullYear();const r=await pool.query("SELECT COALESCE(MAX(CAST(SUBSTRING(receipt_no FROM 10) AS INTEGER)),0) n FROM payments WHERE receipt_no LIKE $1",[`REC-${y}-%`]);return `REC-${y}-${String(Number(r.rows[0].n)+1).padStart(6,'0')}`}
async function audit(u,a,m,id,d=''){await pool.query('INSERT INTO audit(user_id,action,module,record_id,detail) VALUES($1,$2,$3,$4,$5)',[u.id,a,m,id,d])}
function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer /,'');try{req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({error:'Sesión expirada'})}}
function director(req,res,next){if(req.user.role!=='director')return res.status(403).json({error:'Solo el director puede realizar esta acción'});next()}

app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(__dirname,'public')));

app.get('/health',(q,s)=>s.json({ok:true,app:'EmpoderArte',version:'2.1.0'}));
app.post('/api/login',async(q,s)=>{try{const b=q.body||{},r=await pool.query('SELECT * FROM users WHERE email=$1 AND active=1',[b.email||'']);const u=r.rows[0];if(!u||!bcrypt.compareSync(b.password||'',u.password_hash))return s.status(401).json({error:'Usuario o contraseña incorrectos'});await pool.query('UPDATE users SET last_login=CURRENT_TIMESTAMP WHERE id=$1',[u.id]);s.json({token:jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'8h'}),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(e){console.error(e);s.status(500).json({error:'Error del servidor'})}});
app.get('/api/me',auth,(q,s)=>s.json({user:q.user}));
app.get('/api/dashboard',auth,async(q,s)=>{try{const [total,active,overdue,upcoming,revenue,attendance,exp,recent,teachers]=await Promise.all([
 pool.query('SELECT COUNT(*) c FROM students'),pool.query("SELECT COUNT(*) c FROM students WHERE status='Activo'"),pool.query("SELECT COUNT(*) c FROM students WHERE status='Activo' AND due_date IS NOT NULL AND due_date < CURRENT_DATE::text"),pool.query("SELECT COUNT(*) c FROM students WHERE status='Activo' AND due_date IS NOT NULL AND due_date >= CURRENT_DATE::text AND due_date <= (CURRENT_DATE+7)::text"),pool.query("SELECT COALESCE(SUM(amount),0) total FROM payments WHERE paid_at >= date_trunc('month',CURRENT_DATE)::date::text"),pool.query("SELECT COUNT(*) c FROM attendance WHERE attended_at=CURRENT_DATE::text AND status='Presente'"),pool.query("SELECT * FROM students WHERE status='Activo' AND due_date IS NOT NULL AND due_date <= (CURRENT_DATE+7)::text ORDER BY due_date LIMIT 8"),pool.query('SELECT p.*,s.matricula,s.name,s.last_name FROM payments p JOIN students s ON s.id=p.student_id ORDER BY p.id DESC LIMIT 8'),pool.query("SELECT COUNT(*) c FROM teachers WHERE status='Activo'")]);s.json({total:+total.rows[0].c,active:+active.rows[0].c,overdue:+overdue.rows[0].c,upcoming:+upcoming.rows[0].c,revenue:+revenue.rows[0].total,attendance:+attendance.rows[0].c,exp:exp.rows,recent:recent.rows,teachers:+teachers.rows[0].c})}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar el panel'})}});
app.get('/api/students',auth,async(q,s)=>{try{const x=(q.query.q||'').trim();const r=x?await pool.query('SELECT * FROM students WHERE matricula ILIKE $1 OR name ILIKE $2 OR last_name ILIKE $3 ORDER BY id DESC',[`%${x}%`,`%${x}%`,`%${x}%`]):await pool.query('SELECT * FROM students ORDER BY id DESC');const lim=Date.now()+7*864e5;s.json(r.rows.map(a=>({...a,payment_status:a.due_date&&a.status==='Activo'?(new Date(a.due_date+'T12:00:00')<new Date()?'Vencido':new Date(a.due_date+'T12:00:00').getTime()<=lim?'Próximo':'Al corriente'):'Sin fecha'})))}catch(e){console.error(e);s.status(500).json({error:'No se pudieron cargar los alumnos'})}});
app.post('/api/students',auth,async(q,s)=>{try{const b=q.body||{};if(!b.name||!b.last_name)return s.status(400).json({error:'Nombre y apellidos son obligatorios'});const m=await matricula();const r=await pool.query(`INSERT INTO students(matricula,name,last_name,birth_date,phone,email,tutor,tutor_phone,plan,status,enrollment_date,monthly_fee,due_date,benefit_level,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[m,b.name,b.last_name,b.birth_date||null,b.phone||null,b.email||null,b.tutor||null,b.tutor_phone||null,b.plan||'Inicial',b.status||'Activo',b.enrollment_date||today(),+b.monthly_fee||0,b.due_date||nextMonth(today()),b.benefit_level||'Base',b.notes||'']);await audit(q.user,'CREATE','ALUMNOS',r.rows[0].id,'Alta '+m);s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar el alumno'})}});
app.get('/api/students/:id',auth,async(q,s)=>{try{const a=await pool.query('SELECT * FROM students WHERE id=$1',[q.params.id]);if(!a.rowCount)return s.status(404).json({error:'Alumno no encontrado'});const [p,at]=await Promise.all([pool.query('SELECT * FROM payments WHERE student_id=$1 ORDER BY id DESC',[q.params.id]),pool.query('SELECT * FROM attendance WHERE student_id=$1 ORDER BY id DESC LIMIT 20',[q.params.id])]);s.json({...a.rows[0],payments:p.rows,attendance:at.rows})}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar el expediente'})}});
app.put('/api/students/:id',auth,async(q,s)=>{try{const b=q.body||{},old=await pool.query('SELECT * FROM students WHERE id=$1',[q.params.id]);if(!old.rowCount)return s.status(404).json({error:'Alumno no encontrado'});const ks=['name','last_name','birth_date','phone','email','tutor','tutor_phone','plan','status','enrollment_date','monthly_fee','due_date','benefit_level','notes'],set=[],v=[];for(const k of ks)if(k in b){set.push(`${k}=$${v.length+1}`);v.push(k==='monthly_fee'?+b[k]||0:b[k])}if(set.length){v.push(q.params.id);await pool.query(`UPDATE students SET ${set.join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=$${v.length}` ,v);await audit(q.user,'UPDATE','ALUMNOS',q.params.id,'Actualización de expediente')}const r=await pool.query('SELECT * FROM students WHERE id=$1',[q.params.id]);s.json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo actualizar el alumno'})}});
app.post('/api/payments',auth,async(q,s)=>{try{const b=q.body||{},a=await pool.query('SELECT * FROM students WHERE id=$1',[b.student_id]);if(!a.rowCount)return s.status(404).json({error:'Alumno no encontrado'});const st=a.rows[0];if(+b.amount<=0)return s.status(400).json({error:'El monto debe ser mayor a cero'});const rec=await receipt();const r=await pool.query('INSERT INTO payments(receipt_no,student_id,amount,method,concept,paid_at,period,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[rec,st.id,+b.amount,b.method||'Efectivo',b.concept||'Mensualidad',b.paid_at||today(),b.period||'',b.notes||'']);if((b.concept||'').toLowerCase().includes('mensual'))await pool.query('UPDATE students SET due_date=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2',[nextMonth(st.due_date),st.id]);await audit(q.user,'CREATE','PAGOS',r.rows[0].id,'Recibo '+rec);const full=await pool.query('SELECT p.*,s.matricula,s.name,s.last_name FROM payments p JOIN students s ON s.id=p.student_id WHERE p.id=$1',[r.rows[0].id]);s.status(201).json(full.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar el pago'})}});
app.get('/api/payments',auth,async(q,s)=>{try{s.json((await pool.query('SELECT p.*,s.matricula,s.name,s.last_name FROM payments p JOIN students s ON s.id=p.student_id ORDER BY p.id DESC LIMIT 500')).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudieron cargar los pagos'})}});
app.post('/api/attendance',auth,async(q,s)=>{try{const b=q.body||{};if(!b.student_id)return s.status(400).json({error:'Selecciona un alumno'});const r=await pool.query('INSERT INTO attendance(student_id,attended_at,discipline,group_name,status,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[b.student_id,b.attended_at||today(),b.discipline||'',b.group_name||'',b.status||'Presente',b.notes||'']);await audit(q.user,'CREATE','ASISTENCIA',r.rows[0].id,'Registro de asistencia');s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar la asistencia'})}});
app.get('/api/attendance',auth,async(q,s)=>{try{s.json((await pool.query('SELECT a.*,s.matricula,s.name,s.last_name FROM attendance a JOIN students s ON s.id=a.student_id ORDER BY a.id DESC LIMIT 500')).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar la asistencia'})}});
app.get('/api/promotions',auth,async(q,s)=>s.json((await pool.query('SELECT * FROM promotions ORDER BY id DESC')).rows));
app.post('/api/promotions',auth,director,async(q,s)=>{try{const b=q.body||{};if(!b.name)return s.status(400).json({error:'Nombre obligatorio'});const r=await pool.query('INSERT INTO promotions(name,description,discount,kind,expires_at) VALUES($1,$2,$3,$4,$5) RETURNING *',[b.name,b.description||'',+b.discount||0,b.kind||'Porcentaje',b.expires_at||null]);await audit(q.user,'CREATE','PROMOCIONES',r.rows[0].id,'Nueva promoción');s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo crear la promoción'})}});
app.get('/api/benefits',auth,async(q,s)=>s.json((await pool.query('SELECT * FROM benefits ORDER BY id')).rows));
app.get('/api/users',auth,director,async(q,s)=>s.json((await pool.query('SELECT id,name,email,role,active,created_at,last_login FROM users ORDER BY id')).rows));
app.post('/api/users',auth,director,async(q,s)=>{try{const b=q.body||{};const r=await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role',[b.name,b.email,bcrypt.hashSync(b.password,10),b.role||'recepcion']);await audit(q.user,'CREATE','USUARIOS',r.rows[0].id,'Nuevo usuario');s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(400).json({error:'El correo ya existe'})}});
app.get('/api/audit',auth,director,async(q,s)=>s.json((await pool.query('SELECT a.*,u.name user_name FROM audit a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 500')).rows));
app.get('/api/monthly',auth,async(q,s)=>{try{const r=await pool.query(`SELECT id,matricula,name,last_name,phone,plan,monthly_fee,due_date,status,benefit_level FROM students ORDER BY due_date NULLS LAST,id DESC`);const now=new Date();s.json(r.rows.map(x=>{const d=x.due_date?new Date(x.due_date+'T12:00:00'):null;const days=d?Math.ceil((d-now)/86400000):null;return {...x,payment_status:!d?'Sin fecha':days<0?'Vencido':days<=7?'Próximo':'Al corriente',days_remaining:days}}))}catch(e){console.error(e);s.status(500).json({error:'No se pudieron cargar las mensualidades'})}});
app.get('/api/teachers',auth,async(q,s)=>{try{s.json((await pool.query('SELECT * FROM teachers ORDER BY id DESC')).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudieron cargar los maestros'})}});
app.post('/api/teachers',auth,director,async(q,s)=>{try{const b=q.body||{};if(!b.name||!b.last_name)return s.status(400).json({error:'Nombre y apellidos son obligatorios'});const y=new Date().getFullYear();const r0=await pool.query("SELECT COALESCE(MAX(CAST(SUBSTRING(matricula FROM 10) AS INTEGER)),0) n FROM teachers WHERE matricula LIKE $1",[`MAE-${y}-%`]);const n=Number(r0.rows[0].n)+1,m=`MAE-${y}-${String(n).padStart(5,'0')}`;const r=await pool.query('INSERT INTO teachers(matricula,name,last_name,phone,email,discipline,rate_hour,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[m,b.name,b.last_name,b.phone||'',b.email||'',b.discipline||'',+b.rate_hour||0,b.status||'Activo',b.notes||'']);await audit(q.user,'CREATE','MAESTROS',r.rows[0].id,'Alta '+m);s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar el maestro'})}});
app.get('/api/teachers/:id',auth,async(q,s)=>{try{const t=await pool.query('SELECT * FROM teachers WHERE id=$1',[q.params.id]);if(!t.rowCount)return s.status(404).json({error:'Maestro no encontrado'});const a=await pool.query('SELECT * FROM teacher_attendance WHERE teacher_id=$1 ORDER BY id DESC LIMIT 50',[q.params.id]);s.json({...t.rows[0],attendance:a.rows})}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar el maestro'})}});
app.post('/api/teacher-attendance',auth,async(q,s)=>{try{const b=q.body||{},t=await pool.query('SELECT * FROM teachers WHERE id=$1',[b.teacher_id]);if(!t.rowCount)return s.status(404).json({error:'Maestro no encontrado'});if(!b.entry_time&&!b.exit_time)return s.status(400).json({error:'Registra entrada o salida'});const r=await pool.query('INSERT INTO teacher_attendance(teacher_id,attended_at,entry_time,exit_time,discipline,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[b.teacher_id,b.attended_at||today(),b.entry_time||null,b.exit_time||null,b.discipline||t.rows[0].discipline||'',b.notes||'']);await audit(q.user,'CREATE','ASISTENCIA_MAESTROS',r.rows[0].id,'Asistencia '+t.rows[0].matricula);s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar la asistencia del maestro'})}});
app.get('/api/teacher-attendance',auth,async(q,s)=>{try{s.json((await pool.query('SELECT a.*,t.matricula,t.name,t.last_name FROM teacher_attendance a JOIN teachers t ON t.id=a.teacher_id ORDER BY a.id DESC LIMIT 500')).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar la asistencia de maestros'})}});
app.get('/api/locker-plans',auth,async(q,s)=>{try{s.json((await pool.query('SELECT * FROM locker_plans WHERE active=1 ORDER BY months,id')).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudieron cargar los planes de lockers'})}});
app.post('/api/locker-plans',auth,director,async(q,s)=>{try{const b=q.body||{};if(!b.name||!b.months)return s.status(400).json({error:'Nombre y duración son obligatorios'});const r=await pool.query('INSERT INTO locker_plans(name,price,months) VALUES($1,$2,$3) RETURNING *',[b.name,+b.price||0,+b.months]);await audit(q.user,'CREATE','PLANES_LOCKERS',r.rows[0].id,'Nuevo plan de locker');s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(400).json({error:'No se pudo crear el plan; quizá el nombre ya existe'})}});
app.get('/api/lockers',auth,async(q,s)=>{try{s.json((await pool.query(`SELECT l.*,s.matricula,s.name,s.last_name,p.name plan_catalog FROM lockers l LEFT JOIN students s ON s.id=l.student_id LEFT JOIN locker_plans p ON p.id=l.plan_id ORDER BY l.id DESC`)).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudieron cargar los lockers'})}});
app.post('/api/lockers',auth,async(q,s)=>{try{const b=q.body||{};if(!b.number||!b.student_id||!b.plan_id)return s.status(400).json({error:'Número, alumno y plan son obligatorios'});const active=await pool.query("SELECT id FROM lockers WHERE student_id=$1 AND status='Activo'",[b.student_id]);if(active.rowCount)return s.status(400).json({error:'El alumno ya tiene un locker activo'});const p=await pool.query('SELECT * FROM locker_plans WHERE id=$1 AND active=1',[b.plan_id]);if(!p.rowCount)return s.status(404).json({error:'Plan de locker no encontrado'});const plan=p.rows[0];const exists=await pool.query("SELECT id FROM lockers WHERE number=$1 AND status='Activo'",[b.number]);if(exists.rowCount)return s.status(400).json({error:'Ese locker ya está rentado'});const paid=b.paid_at||today(),due=addMonths(paid,plan.months);const r=await pool.query('INSERT INTO lockers(number,student_id,plan_id,plan_name,price,months,paid_at,due_date,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[b.number,b.student_id,plan.id,plan.name,plan.price,plan.months,paid,due,'Activo',b.notes||'']);await pool.query('INSERT INTO locker_payments(locker_id,amount,paid_at,method,concept,period) VALUES($1,$2,$3,$4,$5,$6)',[r.rows[0].id,plan.price,paid,b.method||'Efectivo','Renta de locker',plan.name]);await audit(q.user,'CREATE','LOCKERS',r.rows[0].id,'Renta locker '+b.number);s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo rentar el locker'})}});
app.post('/api/lockers/:id/payment',auth,async(q,s)=>{try{const b=q.body||{},l=await pool.query('SELECT * FROM lockers WHERE id=$1',[q.params.id]);if(!l.rowCount)return s.status(404).json({error:'Locker no encontrado'});const x=l.rows[0],paid=b.paid_at||today(),due=addMonths(x.due_date,x.months);await pool.query('INSERT INTO locker_payments(locker_id,amount,paid_at,method,concept,period) VALUES($1,$2,$3,$4,$5,$6)',[x.id,+b.amount||x.price,paid,b.method||'Efectivo','Renovación de locker',x.plan_name]);const r=await pool.query("UPDATE lockers SET due_date=$1,status='Activo',updated_at=CURRENT_TIMESTAMP WHERE id=$2 RETURNING *",[due,x.id]);await audit(q.user,'CREATE','PAGOS_LOCKERS',x.id,'Renovación locker '+x.number);s.json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar el pago del locker'})}});
app.get('/api/lockers/:id/payments',auth,async(q,s)=>{try{s.json((await pool.query('SELECT * FROM locker_payments WHERE locker_id=$1 ORDER BY id DESC',[q.params.id])).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar el historial del locker'})}});
app.post('/api/lockers/:id/penalty',auth,async(q,s)=>{try{const b=q.body||{},amount=Number(b.amount);if(!amount)return s.status(400).json({error:'Monto inválido'});const r=await pool.query('INSERT INTO locker_penalties(locker_id,amount,reason) VALUES($1,$2,$3) RETURNING *',[q.params.id,amount,b.reason||'Penalización']);await audit(q.user,'CREATE','PENALIZACIONES_LOCKERS',r.rows[0].id,b.reason||'Penalización');s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar la penalización'})}});
app.post('/api/lockers/:id/close',auth,director,async(q,s)=>{try{const r=await pool.query("UPDATE lockers SET status='Finalizado',updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *",[q.params.id]);s.json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo finalizar el locker'})}});
app.get('/api/personal',auth,director,async(q,s)=>{try{s.json((await pool.query('SELECT * FROM personal WHERE status=\'Activo\' ORDER BY id DESC')).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar el personal'})}});
app.post('/api/personal',auth,director,async(q,s)=>{try{const b=q.body||{};if(!b.name||!b.last_name)return s.status(400).json({error:'Nombre y apellidos son obligatorios'});const y=new Date().getFullYear();const r0=await pool.query("SELECT COALESCE(MAX(CAST(SUBSTRING(matricula FROM 10) AS INTEGER)),0) n FROM personal WHERE matricula LIKE $1",[`PER-${y}-%`]);const n=Number(r0.rows[0].n)+1,m=`PER-${y}-${String(n).padStart(5,'0')}`;const r=await pool.query('INSERT INTO personal(matricula,name,last_name,position,area,phone,email,rate_hour) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[m,b.name,b.last_name,b.position||'Recepción',b.area||'',b.phone||'',b.email||'',+b.rate_hour||0]);await audit(q.user,'CREATE','PERSONAL',r.rows[0].id,'Alta '+m);s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar el personal'})}});
app.get('/api/personal/:id',auth,director,async(q,s)=>{try{const r=await pool.query('SELECT * FROM personal WHERE id=$1',[q.params.id]);if(!r.rowCount)return s.status(404).json({error:'Personal no encontrado'});s.json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar el personal'})}});
app.post('/api/personal-attendance',auth,director,async(q,s)=>{try{const b=q.body||{},p=await pool.query('SELECT * FROM personal WHERE id=$1',[b.personal_id]);if(!p.rowCount)return s.status(404).json({error:'Personal no encontrado'});if(!b.entry_time||!b.exit_time)return s.status(400).json({error:'Registra entrada y salida'});const r=await pool.query('INSERT INTO personal_attendance(personal_id,attended_at,entry_time,exit_time,activity) VALUES($1,$2,$3,$4,$5) RETURNING *',[b.personal_id,b.attended_at||today(),b.entry_time,b.exit_time,b.activity||p.rows[0].area||p.rows[0].position]);await audit(q.user,'CREATE','ASISTENCIA_PERSONAL',r.rows[0].id,'Asistencia '+p.rows[0].matricula);s.status(201).json(r.rows[0])}catch(e){console.error(e);s.status(500).json({error:'No se pudo registrar la asistencia del personal'})}});
app.get('/api/payroll',auth,director,async(q,s)=>{try{const rows=[];const teachers=await pool.query("SELECT t.id,t.name,t.last_name,t.rate_hour,COALESCE(SUM(CASE WHEN a.entry_time IS NOT NULL AND a.exit_time IS NOT NULL THEN EXTRACT(EPOCH FROM (('2000-01-01 '||a.exit_time)::timestamp-('2000-01-01 '||a.entry_time)::timestamp))/3600 ELSE 0 END),0) hours FROM teachers t LEFT JOIN teacher_attendance a ON a.teacher_id=t.id AND a.attended_at>=date_trunc('month',CURRENT_DATE)::date::text GROUP BY t.id");teachers.rows.forEach(x=>rows.push({type:'Maestro',name:x.name,last_name:x.last_name,hours:Number(x.hours||0),total:Number(x.hours||0)*Number(x.rate_hour||0)}));const people=await pool.query("SELECT p.id,p.name,p.last_name,p.rate_hour,COALESCE(SUM(CASE WHEN a.entry_time IS NOT NULL AND a.exit_time IS NOT NULL THEN EXTRACT(EPOCH FROM (('2000-01-01 '||a.exit_time)::timestamp-('2000-01-01 '||a.entry_time)::timestamp))/3600 ELSE 0 END),0) hours FROM personal p LEFT JOIN personal_attendance a ON a.personal_id=p.id AND a.attended_at>=date_trunc('month',CURRENT_DATE)::date::text GROUP BY p.id");people.rows.forEach(x=>rows.push({type:'Personal',name:x.name,last_name:x.last_name,hours:Number(x.hours||0),total:Number(x.hours||0)*Number(x.rate_hour||0)}));s.json(rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudo calcular la nómina'})}});
app.get('/api/settings',auth,director,async(q,s)=>{try{const r=await pool.query('SELECT config FROM settings WHERE id=1');s.json(r.rowCount?r.rows[0].config:{})}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar configuración'})}});
app.put('/api/settings',auth,director,async(q,s)=>{try{const b=q.body||{};await pool.query("INSERT INTO settings(id,config) VALUES(1,$1::jsonb) ON CONFLICT(id) DO UPDATE SET config=$1::jsonb,updated_at=CURRENT_TIMESTAMP",[JSON.stringify(b)]);await audit(q.user,'UPDATE','CONFIGURACION',1,'Configuración actualizada');s.json(b)}catch(e){console.error(e);s.status(500).json({error:'No se pudo guardar configuración'})}});
app.get('/api/trash',auth,director,async(q,s)=>{try{s.json((await pool.query('SELECT * FROM trash ORDER BY id DESC LIMIT 500')).rows)}catch(e){console.error(e);s.status(500).json({error:'No se pudo cargar la papelera'})}});
app.post('/api/trash/:id/restore',auth,director,async(q,s)=>{try{const r=await pool.query('SELECT * FROM trash WHERE id=$1',[q.params.id]);if(!r.rowCount)return s.status(404).json({error:'Registro no encontrado'});const x=r.rows[0];if(x.entity_type==='ALUMNO'&&x.data){const d=x.data;await pool.query('INSERT INTO students(id,matricula,name,last_name,birth_date,phone,email,tutor,tutor_phone,plan,status,enrollment_date,monthly_fee,due_date,benefit_level,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) ON CONFLICT(id) DO NOTHING',[d.id,d.matricula,d.name,d.last_name,d.birth_date,d.phone,d.email,d.tutor,d.tutor_phone,d.plan,d.status,d.enrollment_date,d.monthly_fee,d.due_date,d.benefit_level,d.notes]);await pool.query('DELETE FROM trash WHERE id=$1',[x.id]);await audit(q.user,'RESTORE','PAPELERA',x.id,'Alumno restaurado');return s.json({ok:true})}s.status(400).json({error:'Tipo de registro no restaurable'})}catch(e){console.error(e);s.status(500).json({error:'No se pudo restaurar el registro'})}});
app.get('/api/report',auth,async(q,s)=>{try{const [a,b,c,d]=await Promise.all([pool.query('SELECT COUNT(*) n FROM students'),pool.query("SELECT COUNT(*) n FROM students WHERE status='Activo'"),pool.query("SELECT COALESCE(SUM(amount),0) n FROM payments WHERE paid_at >= date_trunc('month',CURRENT_DATE)::date::text"),pool.query("SELECT COUNT(*) n FROM students WHERE status='Activo' AND due_date < CURRENT_DATE::text")]);s.json({alumnos:+a.rows[0].n,activos:+b.rows[0].n,ingresos:+c.rows[0].n,vencidos:+d.rows[0].n})}catch(e){console.error(e);s.status(500).json({error:'No se pudo generar el reporte'})}});
app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));

init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`EmpoderArte V2.1 en puerto ${PORT}`))).catch(e=>{console.error('No se pudo iniciar la base de datos',e);process.exit(1)});
process.on('SIGTERM',async()=>{await pool.end();process.exit(0)});
